services:
  db:
    image: postgres:16-alpine
    container_name: cafeteria_db
    restart: unless-stopped

    environment:
      POSTGRES_DB: cafeteria_db
      POSTGRES_USER: cafeteria_user
      POSTGRES_PASSWORD: cafeteria_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cafeteria_user -d cafeteria_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: